### ISSUE TITLE
[Bug?] Items disappear after the chest is closed

### ISSUE THREAD

**Issue by SheReyy** [StrangeSmell/NoGuiChest#4]
Minecraft: 1.20.1
Forge: 47.2.6
NoGuiChest version: NGC-1.20.1-1.4.2-forge.jar

I don't know if this is intended or not, but the items in the chest become invisible after closing the chest. They can be seen again if a player is lucky enough to pick up an item without seeing it. I'm attaching [a video](https://streamable.com/hxkoto) of this behavior. This becomes even weirder if a double chest is involved.

**Comment by StrangeSmell** [comment]
This is a bug, although I did not reproduce the situation you mentioned when adding the latest versions of Embeddium and Oculus, I still tried to fix it. I built a Alpha version 1.4.4 and released it in modrinth. You can try to resolve it. If it is not resolved, please send me your mods if possible.

**Comment by SheReyy** [comment]
I checked and the issue is still taking place on version 1.4.4. [Here](https://pastebin.com/1wqaE70d)'s my full mod list. I'll also try to check and see what might cause the conflict.

**Comment by StrangeSmell** [comment]
You can compress your mods and send me an email: strange_smell@qq.com.
I'll try to troubleshoot what's causing it.

**Comment by SheReyy** [comment]
I've checked and it looks like TerraFirmaCraft is causing this. It might be TFC's item weight and size feature that's causing this

**Comment by StrangeSmell** [comment]
I see....
It will make the items in the client's chest empty after right clicking, and I will fix it in the latest version 1.4.5.

**Comment by SheReyy** [comment]
I can confirm the issue was solved in version 1.4.5

**Comment by StrangeSmell** [comment]
Sorry, I understand, it was an issue with my mod, the previous fix still flickered a bit, now I've fixed it in 1.4.6!
Thanks for the feedback!
